// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function StartAutoDirector() {
    return window['go']['main']['App']['StartAutoDirector']();
}

export function StopAutoDirector() {
    return window['go']['main']['App']['StopAutoDirector']();
}

export function GetStatus() {
    return window['go']['main']['App']['GetStatus']();
}

export function GetPlayers() {
    return window['go']['main']['App']['GetPlayers']();
}

export function GetEncounters() {
    return window['go']['main']['App']['GetEncounters']();
}

export function GetStatistics() {
    return window['go']['main']['App']['GetStatistics']();
}

export function GetSettings() {
    return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
    return window['go']['main']['App']['SaveSettings'](arg1);
}
