// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function StartAutoDirector() {
    return window['go']['main']['App']['StartAutoDirector']();
}

export function StopAutoDirector() {
    return window['go']['main']['App']['StopAutoDirector']();
}

export function GetStatus() {
    return window['go']['main']['App']['GetStatus']();
}

export function GetPlayers() {
    return window['go']['main']['App']['GetPlayers']();
}

export function GetEncounters() {
    return window['go']['main']['App']['GetEncounters']();
}

export function GetStatistics() {
    return window['go']['main']['App']['GetStatistics']();
}

export function GetSettings() {
    return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
    return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ResetSettings() {
    return window['go']['main']['App']['ResetSettings']();
}

export function ExportSettings() {
    return window['go']['main']['App']['ExportSettings']();
}

export function ImportSettings() {
    return window['go']['main']['App']['ImportSettings']();
}

export function InitFaceitClient(arg1) {
    return window['go']['main']['App']['InitFaceitClient'](arg1);
}

export function FetchFaceitMatchData(arg1) {
    return window['go']['main']['App']['FetchFaceitMatchData'](arg1);
}

export function GetLastMatchData() {
    return window['go']['main']['App']['GetLastMatchData']();
}

export function GetGotvConnectCommand() {
    return window['go']['main']['App']['GetGotvConnectCommand']();
}

export function GetFaceitAPIKey() {
    return window['go']['main']['App']['GetFaceitAPIKey']();
}

export function SaveFaceitAPIKey(arg1) {
    return window['go']['main']['App']['SaveFaceitAPIKey'](arg1);
}

export function GetSecrets() {
    return window['go']['main']['App']['GetSecrets']();
}

export function SaveSecrets(arg1) {
    return window['go']['main']['App']['SaveSecrets'](arg1);
}
